### ISSUE TITLE
erreur

### ISSUE THREAD

**Issue by CyrStyx** [michelbl/better-place#10]
Bonjour, merci pour le travail, je rencontre une erreur et je ne peux accéder aux pages les plus anciennes. Pour exemple, la dernière page https://betterplace.info/recent?&from=44050
l'erreur remontée est 
[query_phase_execution_exception] Result window is too large, from + size must be less than or equal to: [10000] but was [44100]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.

Merci

**Comment by michelbl** [comment]
Effectivement, l'interface actuelle ne permet pas de remonter très loin (voir https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html). Mais augmenter `index.max_result_window` ne me plaît pas trop. Elasticsearch est très bien pour la recherche par mots clefs, mais je ne sais pas si c'est le bon outil pour paginer les résultats par date. Je n'ai pas trop de temps en ce moment pour trouver une solution, je pense m'en occuper vers août/septembre. En attendant, si vous avez besoin des données, je peux vous partager une copie de la base de donnée.

**Comment by CyrStyx** [comment]
Bonjour,

Merci,
Je suis intéressé par une copie de la base de données si possible,

slts

De : Michel Blancard <notifications@github.com>
Envoyé : dimanche 16 juin 2019 12:03
À : michelbl/better-place <better-place@noreply.github.com>
Cc : CyrStyx <tauguere@hotmail.fr>; Author <author@noreply.github.com>
Objet : Re: [michelbl/better-place] erreur (#10)


Effectivement, l'interface actuelle ne permet pas de remonter très loin (voir https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html). Mais augmenter index.max_result_window ne me plaît pas trop. Elasticsearch est très bien pour la recherche par mots clefs, mais je ne sais pas si c'est le bon outil pour paginer les résultats par date. Je n'ai pas trop de temps en ce moment pour trouver une solution, je pense m'en occuper vers août/septembre. En attendant, si vous avez besoin des données, je peux vous partager une copie de la base de donnée.

**Comment by michelbl** [comment]
En prenant le backup le plus récent sur https://betterplace.info/database-backups/, vous pouvez retrouver l'ensemble des métadonnées, et en déduire les urls de l'ensemble des fichiers servis (même ceux qui ne sont pas accessible depuis la pagination).
