### ISSUE TITLE
Récupération des métadonnées impossibles

### ISSUE THREAD

**Issue by yoagauthier** [michelbl/better-place#20]
Bonjour,

Merci bien pour ce projet qui améliore la transparence de la commande publique !

La landing page évoque qu'on peut récupérer les métadonnées sur [https://betterplace.info/database-backups/](https://betterplace.info/database-backups/) mais la page est vide. 

Est-il possible de rendre à nouveau disponibles le(s) élément(s) permettant ce récupération pour après télécharger directement les DCE ?

Bonne journée

**Comment by michelbl** [comment]
Bonsoir, vous avez bien fait d'avoir signalé le problème ! Il reste encore quelques trucs à configurer suite au changement de serveur en fin d'année dernière. La sauvegarde des métadonnées en faisait partie. C'est désormais corrigé, la sauvegarde est hebdomadaire.

**Comment by yoagauthier** [comment]
Super, quelle réactivité, merci bien :-)
